import type { FloodPrediction, GeminiKeySignal } from "@/lib/types";

export interface GitLabIncident {
  issueUrl: string;
  issueId: number;
}

function formatKeySignalsTable(signals: GeminiKeySignal[]): string {
  if (!signals.length) return "_No key signals recorded._";
  const rows = signals
    .map((s) => `| ${s.label} | ${s.value}${s.unit ? " " + s.unit : ""} | ${s.severity} |`)
    .join("\n");
  return `| Signal | Value | Severity |\n|--------|-------|----------|\n${rows}`;
}

const RECOMMENDED_ACTIONS: Record<string, string[]> = {
  critical: [
    "Activate Emergency Operations Center immediately",
    "Issue evacuation orders for low-lying areas",
    "Pre-position rescue boats and emergency supplies",
    "Alert district administration and armed forces",
    "Open emergency shelters at schools and mosques",
    "Broadcast warnings via community radio and loudspeakers",
  ],
  high: [
    "Put emergency teams on standby",
    "Warn residents in flood-prone areas",
    "Check embankment condition",
    "Activate local disaster management committee",
  ],
};

export async function createFloodIncident(
  prediction: FloodPrediction
): Promise<GitLabIncident | null> {
  const token = process.env.GITLAB_TOKEN;
  const projectId = process.env.GITLAB_PROJECT_ID;

  if (!token || !projectId) {
    console.warn("[gitlab] GITLAB_TOKEN or GITLAB_PROJECT_ID not set — skipping incident");
    return null;
  }

  if (prediction.risk_level !== "critical") return null;

  const signals: GeminiKeySignal[] = Array.isArray(prediction.key_signals)
    ? (prediction.key_signals as unknown as GeminiKeySignal[])
    : [];

  const actions =
    RECOMMENDED_ACTIONS[prediction.risk_level] ?? RECOMMENDED_ACTIONS.high;

  const description = [
    `## 🌊 Flood Sentinel — Automated Alert`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Upazila** | ${prediction.upazila} |`,
    `| **District** | ${prediction.district} |`,
    `| **Risk Score** | ${prediction.risk_score}/100 |`,
    `| **Risk Level** | ${prediction.risk_level.toUpperCase()} |`,
    `| **48h Outlook** | ${prediction.risk_48h ?? "N/A"} |`,
    `| **72h Outlook** | ${prediction.risk_72h ?? "N/A"} |`,
    `| **Predicted At** | ${new Date(prediction.predicted_at).toUTCString()} |`,
    ``,
    `### Assessment`,
    ``,
    prediction.reasoning,
    ``,
    `### Bengali Assessment (বাংলা)`,
    ``,
    prediction.reasoning_bn ?? "_Not available_",
    ``,
    `### Key Signals`,
    ``,
    formatKeySignalsTable(signals),
    ``,
    `### Recommended Actions`,
    ``,
    actions.map((a) => `- [ ] ${a}`).join("\n"),
    ``,
    `---`,
    `*Auto-generated by [Flood Sentinel](https://github.com/flood-sentinel) AI Agent · ${new Date().toISOString()}*`,
  ].join("\n");

  const body = {
    title: `🚨 CRITICAL Flood Risk — ${prediction.upazila}, ${prediction.district}`,
    description,
    labels: "flood-alert,critical,automated",
  };

  try {
    const res = await fetch(
      `https://gitlab.com/api/v4/projects/${encodeURIComponent(projectId)}/issues`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "PRIVATE-TOKEN": token,
        },
        body: JSON.stringify(body),
      }
    );

    if (!res.ok) {
      const text = await res.text();
      console.error(`[gitlab] Failed to create issue: ${res.status} ${text}`);
      return null;
    }

    const issue = (await res.json()) as { web_url: string; iid: number };
    return { issueUrl: issue.web_url, issueId: issue.iid };
  } catch (err) {
    console.error("[gitlab] Network error:", err);
    return null;
  }
}
